# Generated by Django 5.0.8 on 2024-09-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_released_date_alter_movie_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='released_date',
            field=models.DateField(auto_now=True),
        ),
    ]
