# Generated by Django 5.0.8 on 2024-09-20 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_alter_movie_released_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='released_date',
        ),
    ]
